### PR TITLE
Created a TO-DO List

### PR DESCRIPTION
**Pull request by MarkL50**
Created a TO-DO List using HTML,CSS and  JavaScript where you can keep in check your days task.

### CODE REVIEW

**Comment by SubhojeetDas1107** [comment]
Can you please provide us screenshots of the site?

**Comment by MarkL50** [comment]
todo1
todo2
todo3

**Comment by SubhojeetDas1107** [comment]
Great work buddy

**Comment by MarkL50** [comment]
Thanks @SubhojeetDas1107 :D

**Pull request merged**
